version: 2.1


orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    executor: heroku/default
    steps: 
      - checkout 
      - heroku/install
      - setup_remote_docker
      - run: 
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            
            
      - run: docker build -t registry.heroku.com/ktor--devops-docker2020/web .
      - run: docker push registry.heroku.com/ktor--devops-docker2020/web
      - run: heroku container:release web --app $HEROKU_APP_NAME
      - run: heroku logs
            
      
workflows:
  build_and_deploy:
    jobs:
      - build:
          context: deployment

        

   
