version: 2.1


orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    executor: heroku/default
    steps: 
      - checkout 
      - heroku/install
      - run: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      
workflows:
  build_and_deploy:
    jobs:
      - build:
          context: deployment

        

   
