version: 2.1


orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    executor: heroku/default
    steps: 
      - checkout 
      - heroku/install
      - run: 
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            docker build -t registry.heroku.com/ktor--devops-docker2020/web .
            docker push registry.heroku.com/ktor--devops-docker2020/web
            heroku container:release web
            
      
workflows:
  build_and_deploy:
    jobs:
      - build:
          context: deployment

        

   
