version: 2.1



jobs:
  build:
    machine: 
      image: ubuntu-1604:202004-01
    steps: 
      - checkout 
      - docker build .
      - ls 
workflows:
  build_and_deploy:
    jobs:
      - build

   